name: Build macOS & Windows wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheel_macOS:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install packages
        run: brew install coreutils

      - name: Build wheel
        run: ./scripts/build-wheels-macOS.sh

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist

  build_wheel_windows:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build wheel
        run: .\scripts\build-wheels-windows.bat

      - uses: actions/upload-artifact@v2
        with:
          path: .\dist

  test_wheel:
    name: Test Python ${{ matrix.python }} wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: 
      - build_wheel_windows
      - build_wheel_macOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, windows-2019]
        python: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Install mrob & numpy
        if: matrix.os == 'windows-2019'
        run: |
          python -m pip install .\artifact\$(dir artifact -Name | findstr mrob-.*-win_amd64.whl) numpy pytest

      - name: Install mrob & numpy
        if: matrix.os == 'macos-10.15'
        run: |
          python -m pip install ./artifact/mrob-*-macosx_10_9_x86_64.whl numpy pytest

      - name: "Python unit tests"
        run: |
          python -m pytest mrobpy

  publish_pypi:
    name: Publish macOS & Windows wheels to PyPI
    needs: test_wheel
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifact/

  publish-github-release:
    name: Publish macOS & Windows wheels to GitHub Releases
    needs: test_wheel
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - uses: softprops/action-gh-release@v1
        with:
          files: artifact/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
