name: Build wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build mrob project 
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./lib
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Install required packages from distro"
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends git build-essential g++ cmake python3-distutils python3-dev python3-numpy python3-pip
            python3 -m pip install pytest

      - name: "Configure and build native mrob library with Python bindings"
        run: |
            mkdir -p build
            cmake -S $PWD -B $PWD/build \
             -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$PWD/bin \
             -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$PWD/lib \
            && cmake --build build -j $(nproc)  

      - name: "C++ unit tests"
        run: make test -C build

      - name: "Python unit tests"
        run: python3 -m pytest mrobpy

      - name: "Setup __init__.py"
        run: ./scripts/init.sh

      - uses: actions/upload-artifact@v2
        with:
          name: __init__.py
          path: ./__init__.py

  build_wheel_linux:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: quay.io/pypa/manylinux2010_x86_64
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: "Install additional utils"
        run: yum install -y chrpath git openssh-clients

      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: __init__.py
          path: ./

      - name: "Install fresh CMake into ManyLinux container"
        run: |
            env pybin=$(LANG=C ls -d1r /opt/python/cp3*/bin | head -n 1) bash -c '$pybin/python -m pip install cmake && mkdir -p /usr/local/bin && ln -svf $pybin/cmake /usr/local/bin/cmake'
            cmake --version

      - name: "Build Python wheels"
        run: scripts/build-wheels-linux.sh

      - uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./build/wheelhouse


  build_wheel_macOS:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: __init__.py
          path: ./

      - name: Install packages
        run: brew install coreutils

      - name: Build wheel
        run: ./scripts/build-wheels-macOS.sh

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist

  build_wheel_windows:
    name: Build wheel on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: __init__.py
          path: ./

      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build wheel
        run: .\scripts\build-wheels-windows.bat

      - uses: actions/upload-artifact@v2
        with:
          path: .\dist

  test_wheel:
    name: Test Python ${{ matrix.python }} wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: 
      - build_wheel_linux
      - build_wheel_macOS
      - build_wheel_windows
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15, windows-2019]
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ./artifact

      - name: Install mrob & numpy
        if: matrix.os == 'windows-2019'
        run: |
          python -m pip install .\artifact\$(dir artifact -Name | findstr mrob-.*-win_amd64.whl) numpy pytest

      - name: Install mrob & numpy
        if: matrix.os == 'macos-10.15'
        run: |
          python -m pip install ./artifact/mrob-*-macosx_10_9_x86_64.whl numpy pytest

      - name: Install mrob & numpy
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install ./artifact/mrob-*-manylinux*.whl numpy pytest

      - name: "Python unit tests"
        run: |
          python -m pytest mrobpy

  publish_pypi:
    name: Publish macOS & Windows wheels to PyPI
    needs: test_wheel
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifact/

  publish-github-release:
    name: Publish macOS & Windows wheels to GitHub Releases
    needs: test_wheel
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - uses: softprops/action-gh-release@v1
        with:
          files: artifact/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
